import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path:'../../public/local fonts/SolaimanLipi/SolaimanLipi-Thin.ttf',
      weight: '100',
      style: 'thin',
    },
    {
      path:'../../public/local fonts/SolaimanLipi/SolaimanLipi-Normal.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path:'../../public/local fonts/SolaimanLipi/SolaimanLipi-Bold.ttf',
      weight: '700',
      style: 'bold',
    }
  ]
})


export const metadata = {
  title: "Next.js Font Optimization",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>
        {children}
      </body>
    </html>
  );
}