import localFont from "next/font/local";
import "./globals.css";

// সোলাইমানলিপি ফন্ট সেটআপ (Multiple weights সহ)
const solaimanFont = localFont({
  src: [
    {
      path:'../../public/local fonts/SolaimanLipi/SolaimanLipi-Thin.ttf',
      weight: '100',
      style: 'thin',
    },
    {
      path:'../../public/local fonts/SolaimanLipi/SolaimanLipi-Normal.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path:'../../public/local fonts/SolaimanLipi/SolaimanLipi-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
  ],
  variable: '--font-solaiman',
  display: 'swap',
});

// নিকশ ফন্ট সেটআপ
const nikoshFont = localFont({
  src: [
    {
      path: '../../public/local fonts/Nikosh/Nikosh.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-nikosh',
  display: 'swap',
})

export { nikoshFont, solaimanFont };


export const metadata = {
  title: "Next.js Font Optimization",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${solaimanFont.variable} ${nikoshFont.variable}`}>
      <body className={solaimanFont.className}>
        {children}
      </body>
    </html>
  );
}